services:
  gunicorn: &app_c
    build: .
    command: "gunicorn --bind 0.0.0.0:8000 --workers 3 stagingserver.wsgi:application"
    volumes:
      - "./db.sqlite3:/STAGING_APP/db.sqlite3:rw"
      - "./STAGING_DIR:/STAGING_DIR"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./staging_logs.out:/STAGING_APP/staging_logs.out"
      - "/etc/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "/etc/nginx/sites-available:/etc/nginx/sites-available"
    environment:
      - DEBUG=0
    depends_on:
      - redis
    # ports:
      # - '8000:8000'
  daphne:
    <<: *app_c
    command: "daphne stagingserver.asgi:application --bind 0.0.0.0 --port 8001"
  redis:
    image: redis:alpine
  celery:
    build: .
    command: "celery -A stagingserver worker -l debug >> celery_logs.out"
    volumes:
      - "./db.sqlite3:/STAGING_APP/db.sqlite3:rw"
      - "./STAGING_DIR:/STAGING_DIR"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./celery_logs.out:/STAGING_APP/celery_logs.out"
      - "/etc/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "/etc/nginx/sites-available:/etc/nginx/sites-available"
    depends_on:
      - gunicorn
      - redis
  nginx:
    image: nginx
    volumes:
      - './docker/dev.conf:/etc/nginx/conf.d/default.conf:ro'
      - './assets:/var/www/public/:ro'
    ports:
      - '127.0.0.1:8000:8000'
  socat:
    image: alpine/socat
    command: "TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
