services:
  gunicorn: &app_c
    build: .
    command: "gunicorn --bind 127.0.0.1:7000 --workers 3 stagingserver.wsgi:application"
    volumes:
      - "./db.sqlite3:/STAGING_APP/db.sqlite3:rw"
      - "./STAGING_DIR:/STAGING_DIR"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "/etc/nginx/sites-available:/etc/nginx/sites-available"
    environment:
      - DEBUG=0
    depends_on:
      - redis
    network_mode: host
  daphne:
    <<: *app_c
    command: "daphne stagingserver.asgi:application --bind 127.0.0.1 --port 7001"
  redis:
    image: redis:alpine
    network_mode: host
  celery:
    <<: *app_c
    command: "celery -A stagingserver worker -l info"
    depends_on:
      - redis
  socat:
    image: alpine/socat
    command: "TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: host