services:
  gunicorn: &app_c
    build: .
    command: "/bin/bash -c 'chmod +x ./deploy/gunicorn.sh && ./deploy/gunicorn.sh'"
    volumes:
      - "./db.sqlite3:/STAGING_APP/db.sqlite3:rw"
      - "./STAGING_DIR:/STAGING_DIR"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "/etc/nginx/sites-available:/etc/nginx/sites-available"
    environment:
      - DEBUG=0
    depends_on:
      - redis
    network_mode: host
    restart: always
  daphne:
    <<: *app_c
    command: "daphne stagingserver.asgi:application --bind 127.0.0.1 --port 7001"
    depends_on:
      - gunicorn
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "127.0.0.1:6380:6379"
  celery:
    <<: *app_c
    command: "celery -A stagingserver worker -l info"
    depends_on:
      - redis
  socat:
    image: alpine/socat
    command: "TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "127.0.0.1:2375:2375"
    restart: always
