# Generated by Django 4.2.1 on 2024-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcs', models.TextField(choices=[('github', 'github'), ('gitlab', 'gitlab'), ('git.iris', 'git.iris')])),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('user_name', models.TextField(max_length=100, verbose_name='Organisation or User')),
                ('repo_name', models.TextField(max_length=100, verbose_name='Repository Name')),
                ('git_url', models.URLField(verbose_name='Git URL')),
                ('access_token', models.TextField(blank=True, max_length=100, null=True, verbose_name='Access Token')),
                ('branch', models.TextField(max_length=100, verbose_name='Branch')),
                ('default_branch', models.TextField(default='main', max_length=100, verbose_name='Default Branch')),
                ('docker_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Docker Image')),
                ('docker_network', models.TextField(default='bridge', max_length=100, verbose_name='Docker Network')),
                ('docker_volumes', models.TextField(default='{}', max_length=500, verbose_name='Docker Volumes')),
                ('docker_env_vars', models.TextField(default='{}', max_length=500, verbose_name='Docker Environment Variables')),
                ('internal_port', models.IntegerField(default='80', verbose_name='Internal Port')),
                ('dockerfile_path', models.TextField(blank=True, default='Dockerfile', max_length=100, null=True, verbose_name='Dockerfile Path')),
            ],
        ),
    ]
