# Generated by Django 4.1.4 on 2023-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='dockerfile_path',
            field=models.TextField(blank=True, default='Dockerfile', max_length=100, null=True, verbose_name='Dockerfile Path'),
        ),
    ]
