# Generated by Django 4.2.1 on 2024-01-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.TextField(choices=[('github', 'Github'), ('gitlab', 'Gitlab'), ('other', 'Other')])),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('organisation_or_user', models.TextField(max_length=100, verbose_name='Organisation or User')),
                ('git_repo_url', models.URLField(verbose_name='Git URL')),
                ('access_token', models.TextField(blank=True, max_length=50, null=True, verbose_name='Access Token')),
                ('default_branch', models.TextField(default='main', max_length=50, verbose_name='Default Branch')),
                ('docker_image', models.TextField(blank=True, max_length=100, verbose_name='Docker Image')),
                ('docker_network', models.TextField(default='bridge', max_length=100, verbose_name='Docker Network')),
                ('docker_volumes', models.TextField(default='{}', max_length=500, verbose_name='Docker Volumes')),
                ('docker_env_vars', models.TextField(default='{}', max_length=500, verbose_name='Docker Environment Variables')),
                ('internal_port', models.IntegerField(default='80', verbose_name='Internal Port')),
                ('dockerfile_path', models.TextField(blank=True, max_length=100, verbose_name='Dockerfile Path')),
            ],
        ),
        migrations.CreateModel(
            name='RunningInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.TextField()),
                ('owner', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('STOPPED', 'Stopped'), ('DEPLOYING', 'Deploying')], default='PENDING')),
                ('organisation', models.TextField()),
                ('repo_name', models.TextField()),
                ('social', models.TextField()),
                ('exposed_port', models.IntegerField(default=3000)),
                ('dockerfile_path', models.TextField(blank=True)),
                ('internal_port', models.IntegerField(default=80)),
                ('deployed_url', models.URLField(blank=True, max_length=255)),
                ('project_url', models.URLField(blank=True, max_length=255)),
                ('app_container_name', models.TextField(blank=True)),
                ('db_container_name', models.TextField(blank=True)),
                ('app_docker_image', models.TextField(blank=True)),
                ('app_dockerfile', models.TextField(blank=True)),
                ('db_docker_image', models.TextField(blank=True)),
                ('app_env_vars', models.TextField(blank=True, null=True)),
                ('db_env_vars', models.TextField(blank=True, null=True)),
                ('deployment_id', models.TextField(max_length=64, unique=True)),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repositories.repository')),
            ],
        ),
    ]
