# Generated by Django 4.2.1 on 2024-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runninginstance',
            name='app_docker_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runninginstance',
            name='db_docker_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
