# Generated by Django 4.2.1 on 2024-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_runninginstance_app_docker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='log_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
