# Generated by Django 4.1.4 on 2022-12-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_runninginstance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runninginstance',
            name='user',
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='organisation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='repo_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='social',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
