# Generated by Django 4.1.4 on 2023-01-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_runninginstance_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.TextField(choices=[('github', 'Github'), ('gitlab', 'Gitlab'), ('other', 'Other')])),
                ('organisation_or_user', models.TextField(max_length=100, verbose_name='Organisation or User')),
                ('git_repo_url', models.URLField(verbose_name='Git URL')),
                ('access_token', models.TextField(max_length=50, verbose_name='Access Token')),
                ('default_branch', models.TextField(default='main', max_length=50, verbose_name='Default Branch')),
                ('docker_image', models.TextField(default='ubuntu:latest', max_length=100, verbose_name='Docker Image')),
                ('docker_network', models.TextField(default='bridge', max_length=100, verbose_name='Docker Network')),
                ('docker_volumes', models.TextField(default='{}', max_length=500, verbose_name='Docker Volumes')),
                ('internal_port', models.IntegerField(default='80', verbose_name='Internal Port')),
                ('dockerfile_path', models.TextField(blank=True, max_length=100, verbose_name='Dockerfile Path')),
            ],
        ),
    ]
