# Generated by Django 4.2.1 on 2024-01-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_runninginstance_log_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='branch_deploy_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
