# Generated by Django 4.1.4 on 2023-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deploytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytemplate',
            name='name',
            field=models.TextField(default='defaultname', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
