# Generated by Django 4.1.4 on 2023-01-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_runninginstance_exposed_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploytemplate',
            name='docker_image',
            field=models.TextField(blank=True, max_length=100, verbose_name='Docker Image'),
        ),
        migrations.AlterField(
            model_name='runninginstance',
            name='status',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('STOPPED', 'Stopped'), ('DEPLOYING', 'Deploying')], default='PENDING'),
        ),
    ]
