# Generated by Django 4.1.4 on 2023-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_deploytemplate_docker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='dockerfile_path',
            field=models.TextField(blank=True),
        ),
    ]
