# Generated by Django 4.1.4 on 2023-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_runninginstance_dockerfile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='dockerfile_path',
            field=models.TextField(blank=True),
        ),
    ]
