# Generated by Django 4.1.4 on 2023-01-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_runninginstance_dockerfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runninginstance',
            name='dockerfile_path',
            field=models.TextField(default='dockerfile_path'),
        ),
    ]
