# Generated by Django 4.1.4 on 2023-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_runninginstance_dockerfile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='app_container_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='db_container_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='deployed_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='project_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
