# Generated by Django 4.1.4 on 2023-05-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_runninginstance_app_container_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='app_docker_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='db_docker_image',
            field=models.TextField(blank=True),
        ),
    ]
