# Generated by Django 4.2.1 on 2023-10-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_runninginstance_app_docker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='app_env_vars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
