# Generated by Django 4.2.1 on 2024-01-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_git_url', models.URLField(blank=True, max_length=255)),
                ('repo_name', models.TextField()),
                ('repo_username', models.TextField(blank=True)),
                ('access_token', models.TextField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING')),
                ('dockerfile_path', models.TextField(blank=True)),
                ('app_env_vars', models.TextField(blank=True, null=True)),
                ('db_image', models.TextField(blank=True)),
                ('db_env_vars', models.TextField(blank=True, null=True)),
                ('internal_port', models.IntegerField(default=80)),
                ('deployments', models.PositiveIntegerField(default=0)),
                ('deployer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
