# Generated by Django 4.2.1 on 2024-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='app_env_db_host_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
