# Generated by Django 4.2.1 on 2024-01-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_app_env_db_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='app_env_db_host_key',
            field=models.TextField(blank=True, default='DEV_DB_HOST'),
        ),
    ]
